# Generated by Django 3.2.12 on 2022-02-02 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companycategory',
            old_name='staus',
            new_name='status',
        ),
    ]
