# Generated by Django 3.2.12 on 2022-02-02 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_rename_staus_companycategory_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventcategory',
            old_name='staus',
            new_name='status',
        ),
    ]
