# Generated by Django 3.2.12 on 2022-02-02 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_rename_staus_eventcategory_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='webiste',
            new_name='website',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='webiste',
            new_name='website',
        ),
    ]
