# Generated by Django 3.2.12 on 2022-02-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20220202_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='skype',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
