# Generated by Django 3.2.12 on 2022-02-02 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_rename_phone_company_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='coordinator',
        ),
    ]
