# Generated by Django 3.2.12 on 2022-02-03 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_rename_phone_contact_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='title',
            new_name='designation',
        ),
    ]
