# Generated by Django 3.2.12 on 2022-02-03 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_rename_title_contact_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='name_prefix',
            field=models.CharField(choices=[('Mr.', 'Mr.'), ('Ms.', 'Ms.'), ('Mrs.', 'Mrs.'), ('Miss.', 'Miss.'), ('Mx.', 'Mx'), ('Dr.', 'Dr.')], max_length=5),
        ),
    ]
