# Generated by Django 3.2.12 on 2022-02-03 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_alter_contact_name_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='skype',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
