# Generated by Django 3.2.12 on 2022-02-03 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_auto_20220203_1050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='circle',
            old_name='desciption',
            new_name='description',
        ),
    ]
