# Generated by Django 3.2.12 on 2022-02-03 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_rename_desciption_circle_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Inactive')], default=1),
            preserve_default=False,
        ),
    ]
