# Generated by Django 3.2.12 on 2022-02-03 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_alter_circleclient_circle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circleclient',
            name='circle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circle_contact', to='crm.circle'),
        ),
    ]
