# Generated by Django 3.2.12 on 2022-02-03 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_alter_circleclient_circle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='client',
        ),
    ]
