# Generated by Django 3.2.12 on 2022-02-03 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_remove_event_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='duration',
            field=models.CharField(choices=[('15 minutes', '15 minutes'), ('30 minutes', '30 minutes'), ('45 minutes', '45 minutes'), ('1 hour', '1 hour'), ('1 hour 15 minutes', '1 hour 15 minutes'), ('1 hour 30 minutes', '1 hour 30 minutes'), ('1 hour 45 minutes', '1 hour 45 minutes'), ('2 hour', '2 hour'), ('2 hours 15 minutes', '2 hours 15 minutes'), ('2 hours 30 minutes', '2 hours 30 minutes'), ('2 hours 45 minutes', '2 hours 45 minutes'), ('3 hour', '3 hour'), ('3 hours 15 minutes', '3 hours 15 minutes'), ('3 hours 30 minutes', '3 hours 30 minutes'), ('3 hours 45 minutes', '3 hours 45 minutes'), ('4 hour', '4 hour'), ('4 hours 15 minutes', '4 hours 15 minutes'), ('4 hours 30 minutes', '4 hours 30 minutes'), ('4 hours 45 minutes', '4 hours 45 minutes'), ('5 hour', '5 hour'), ('5 hours 15 minutes', '5 hours 15 minutes'), ('5 hours 30 minutes', '5 hours 30 minutes'), ('5 hours 45 minutes', '5 hours 45 minutes'), ('6 hour', '6 hour'), ('6 hours 15 minutes', '6 hours 15 minutes'), ('6 hours 30 minutes', '6 hours 30 minutes'), ('6 hours 45 minutes', '6 hours 45 minutes'), ('7 hour', '7 hour'), ('7 hours 15 minutes', '7 hours 15 minutes'), ('7 hours 30 minutes', '7 hours 30 minutes'), ('7 hours 45 minutes', '7 hours 45 minutes'), ('8 hour', '8 hour'), ('8 hours 15 minutes', '8 hours 15 minutes'), ('8 hours 30 minutes', '8 hours 30 minutes'), ('8 hours 45 minutes', '8 hours 45 minutes'), ('9 hour', '9 hour'), ('9 hours 15 minutes', '9 hours 15 minutes'), ('9 hours 30 minutes', '9 hours 30 minutes'), ('9 hours 45 minutes', '9 hours 45 minutes'), ('10 hour', '10 hour'), ('10 hours 15 minutes', '10 hours 15 minutes'), ('10 hours 30 minutes', '10 hours 30 minutes'), ('10 hours 45 minutes', '10 hours 45 minutes'), ('11 hour', '11 hour'), ('11 hours 15 minutes', '11 hours 15 minutes'), ('11 hours 30 minutes', '11 hours 30 minutes'), ('11 hours 45 minutes', '11 hours 45 minutes'), ('12 hour', '12 hour')], max_length=100),
        ),
    ]
