# Generated by Django 3.2.12 on 2022-03-07 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0021_message_messageattachment_messagereciever'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagereciever',
            name='contact',
        ),
        migrations.AddField(
            model_name='messagereciever',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='messageattachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
    ]
