# Generated by Django 3.2.12 on 2022-06-17 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0022_auto_20220307_2305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Inactive')], default=1)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rate_type', models.IntegerField(choices=[(1, 'Percentage %'), (2, 'Amount #')])),
            ],
            options={
                'verbose_name': 'Discount',
                'verbose_name_plural': 'Discounts',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Paid')], default=1)),
                ('invoice_number', models.CharField(max_length=1000)),
                ('due_added', models.DateTimeField(auto_now_add=True)),
                ('internal_notes', models.TextField(blank=True, null=True)),
                ('terms_and_conditions', models.TextField(blank=True, null=True)),
                ('payment_description', models.TextField(blank=True, null=True)),
                ('sub_total', models.DecimalField(blank=True, decimal_places=2, max_digits=999, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True)),
                ('discounts_total', models.DecimalField(blank=True, decimal_places=2, max_digits=999, null=True)),
                ('grand_total', models.DecimalField(blank=True, decimal_places=2, max_digits=999, null=True)),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
            },
        ),
        migrations.CreateModel(
            name='InvoiceSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('invoice_prefix', models.CharField(max_length=5)),
                ('email_notification', models.BooleanField(default=False)),
                ('terms_and_conditions', models.TextField(blank=True, null=True)),
                ('payment_description', models.TextField(blank=True, null=True)),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='Invoice_Logos/')),
            ],
            options={
                'verbose_name': 'Invoice Setting',
                'verbose_name_plural': 'Invoice Settings',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Inactive')], default=1)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Inactive')], default=1)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('apply_tax', models.IntegerField(choices=[(1, 'Apply After Discount'), (2, 'Global Tax')])),
            ],
            options={
                'verbose_name': 'Tax',
                'verbose_name_plural': 'Taxes',
            },
        ),
        migrations.CreateModel(
            name='InvoiceTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxes', to='crm.invoice')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.tax')),
            ],
            options={
                'verbose_name': 'Invoice Tax',
                'verbose_name_plural': 'Invoice Taxes',
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='crm.invoice')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.item')),
            ],
            options={
                'verbose_name': 'Invoice Item',
                'verbose_name_plural': 'Invoice Items',
            },
        ),
        migrations.CreateModel(
            name='InvoiceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='invoice_files')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='crm.invoice')),
            ],
            options={
                'verbose_name': 'Invoice File',
                'verbose_name_plural': 'Invoice Files',
            },
        ),
        migrations.CreateModel(
            name='InvoiceDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.discount')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='crm.invoice')),
            ],
            options={
                'verbose_name': 'Invoice Discount',
                'verbose_name_plural': 'Invoice Discounts',
            },
        ),
        migrations.CreateModel(
            name='InvoiceClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='crm.contact')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='crm.invoice')),
            ],
            options={
                'verbose_name': 'Invoice Client',
                'verbose_name_plural': 'Invoice Clients',
            },
        ),
    ]
