# Generated by Django 3.2.12 on 2022-06-17 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0023_discount_invoice_invoiceclient_invoicediscount_invoicefile_invoiceitem_invoicesetting_invoicetax_ite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
