# Generated by Django 3.2.12 on 2022-06-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0024_alter_item_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tax',
            name='rate',
        ),
        migrations.AddField(
            model_name='tax',
            name='percentage',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
