# Generated by Django 3.2.12 on 2022-06-17 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0025_auto_20220617_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='rate',
        ),
        migrations.AddField(
            model_name='discount',
            name='percentage',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
