# Generated by Django 3.2.12 on 2022-06-17 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0026_auto_20220617_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='percentage',
            new_name='rate',
        ),
    ]
