# Generated by Django 3.2.12 on 2022-06-17 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0028_remove_invoicesetting_email_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='rate',
            new_name='percentage',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='rate_type',
        ),
        migrations.RemoveField(
            model_name='tax',
            name='apply_tax',
        ),
    ]
