# Generated by Django 3.2.12 on 2022-06-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0029_auto_20220617_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='taxes_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=999, null=True),
        ),
    ]
