# Generated by Django 3.2.12 on 2022-06-18 21:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0030_invoice_taxes_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
