# Generated by Django 3.2.12 on 2022-06-18 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0031_alter_invoice_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='title',
            field=models.CharField(default='Dummy', max_length=200),
            preserve_default=False,
        ),
    ]
