# Generated by Django 3.2.12 on 2022-06-18 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0032_invoice_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='due_added',
            new_name='due_date',
        ),
    ]
