# Generated by Django 3.2.12 on 2022-06-18 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0033_rename_due_added_invoice_due_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoicetax',
            old_name='item',
            new_name='tax',
        ),
    ]
