# Generated by Django 3.2.12 on 2022-06-19 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0034_rename_item_invoicetax_tax'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Paid')], default=1)),
                ('title', models.CharField(max_length=200)),
                ('estimate_number', models.CharField(max_length=1000)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField(auto_now_add=True)),
                ('internal_notes', models.TextField(blank=True, null=True)),
                ('terms_and_conditions', models.TextField(blank=True, null=True)),
                ('payment_description', models.TextField(blank=True, null=True)),
                ('sub_total', models.DecimalField(blank=True, decimal_places=2, max_digits=999, null=True)),
                ('taxes_total', models.DecimalField(blank=True, decimal_places=2, max_digits=999, null=True)),
                ('discounts_total', models.DecimalField(blank=True, decimal_places=2, max_digits=999, null=True)),
                ('grand_total', models.DecimalField(blank=True, decimal_places=2, max_digits=999, null=True)),
            ],
            options={
                'verbose_name': 'Estimate',
                'verbose_name_plural': 'Estimates',
            },
        ),
        migrations.CreateModel(
            name='EstimateSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('estimate_prefix', models.CharField(max_length=5)),
                ('terms_and_conditions', models.TextField(blank=True, null=True)),
                ('payment_description', models.TextField(blank=True, null=True)),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='Invoice_Logos/')),
            ],
            options={
                'verbose_name': 'Estimate Setting',
                'verbose_name_plural': 'Estimate Settings',
            },
        ),
        migrations.CreateModel(
            name='EstimateTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimate_taxes', to='crm.estimate')),
                ('tax', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.tax')),
            ],
            options={
                'verbose_name': 'Estimate Tax',
                'verbose_name_plural': 'Estimate Taxes',
            },
        ),
        migrations.CreateModel(
            name='EstimateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimate_items', to='crm.estimate')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.item')),
            ],
            options={
                'verbose_name': 'Estimate Item',
                'verbose_name_plural': 'Estimate Items',
            },
        ),
        migrations.CreateModel(
            name='EstimateFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='estimate_files')),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimate_files', to='crm.estimate')),
            ],
            options={
                'verbose_name': 'Estimate File',
                'verbose_name_plural': 'Estimate Files',
            },
        ),
        migrations.CreateModel(
            name='EstimateDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.discount')),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimate_discounts', to='crm.estimate')),
            ],
            options={
                'verbose_name': 'Estimate Discount',
                'verbose_name_plural': 'Estimate Discounts',
            },
        ),
        migrations.CreateModel(
            name='EstimateClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.contact')),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimate_clients', to='crm.estimate')),
            ],
            options={
                'verbose_name': 'Estimate Client',
                'verbose_name_plural': 'Estimate Clients',
            },
        ),
    ]
