# Generated by Django 3.2.12 on 2022-06-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0037_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_for',
            field=models.IntegerField(choices=[(1, 'Invoice'), (2, 'Estimate')]),
        ),
    ]
