# Generated by Django 3.2.12 on 2023-11-04 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0038_alter_document_document_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='related_invoices', to='crm.contact'),
            preserve_default=False,
        ),
    ]
