# Generated by Django 3.2.12 on 2023-11-04 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0039_invoice_client'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InvoiceClient',
        ),
    ]
