# Generated by Django 3.2.12 on 2023-11-04 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0041_auto_20231104_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='type',
        ),
    ]
