# Generated by Django 3.2.12 on 2023-11-04 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0042_remove_profile_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='related_estimates', to='crm.contact'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='EstimateClient',
        ),
    ]
