# Generated by Django 3.2.12 on 2023-11-13 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0043_auto_20231104_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='status',
            field=models.IntegerField(choices=[(1, 'Open'), (2, 'Accepted'), (2, 'Rejected')], default=1),
        ),
    ]
