# Generated by Django 3.2.12 on 2023-11-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0044_alter_estimate_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='due_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateTimeField(),
        ),
    ]
